### ISSUE TITLE
Sequence `\; \textsc{...}` broken in tabulars 

### ISSUE THREAD

**Issue by kopeckyf** [adamb924/ot-tableau#1] opened 2021-11-30 08:18 UTC
Hey there, 

the sequence `\; \textsc{...}` is broken in `tabulars` when `ot-tableau` is loaded. For example:

```latex
\documentclass{article}
\begin{document}
\begin{tabular}{ll}
  Hello\; \textsc{hello} & World
\end{tabular}
\end{document}
```

compiles as expected. But adding `\usepackage{ot-tableau}` breaks the code:

```latex
! Argument of \textsc  has an extra }.
<inserted text> 
                \par 
l.5 ^^I^^IHello\; \textsc
```

I scanned `ot-tableau`'s source code and some of its dependencies for definitions of `\;` but didn't find any.

Best,
Felix

**Comment by kopeckyf** [comment] 2021-11-30 08:19
(My ot-tableau version is 2021-05-19)

**Comment by adamb924** [comment] 2021-11-30 08:59
Thank you for discovering that. I will have a look, but my initial thought is that some package that `ot-tableau` loads is creating the error, since (as you say) I don't define that macro. In the meantime I noticed that the problem can be addressed by adding curly braces:

	\documentclass{article}
	\usepackage{ot-tableau}
	\begin{document}
	\begin{tabular}{ll}
	  Hello\;{} \textsc{hello} & World
	\end{tabular}
	\end{document}

**Comment by kopeckyf** [comment] 2021-11-30 09:06
Thanks for the quick reply! 

Inserting `{}` is helpful! 

I also noticed that the effects of `\;` seem to be disabled, i.e. no space is inserted by the command. This might have to do with the re-definition of `\;` by some other package.

**Comment by adamb924** [comment] 2021-11-30 09:14
It turned out to be a problem with the `tipa` package, which is loaded by default. You can use the `notipa` option to solve this. (Mnemonic fail: `notipa` was intended as “no tipa” but looks like “not ipa”!)

	\documentclass{article}
	\usepackage[notipa]{ot-tableau}
	\begin{document}
	\begin{tabular}{ll}
	  Hello\; \textsc{hello} & World
	\end{tabular}
	\end{document}

As I imagine `tipa` is used very rarely now that we have XeTeX, I guess I'll eventually make it not load `tipa` by default.

**Closed as completed by adamb924** 2021-11-30 09:14 UTC

**Comment by kopeckyf** [comment] 2021-11-30 09:16
Well spotted! Thanks a lot!
